name = "ImmersedLayers"
uuid = "cdc13194-334e-4e1c-bc8d-fc3a28509c85"
authors = ["Jeff Eldredge <jdeldre@g.ucla.edu>"]
repo = "https://github.com/JuliaIBPM/ImmersedLayers.jl.git"
version = "0.5.0"

[deps]
CartesianGrids = "3e975e5d-2cf8-4263-9573-8460aaf534d9"
CatViews = "81a5f4ea-a946-549a-aa7e-2a7f63a27d31"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
ConstrainedSystems = "c257ce95-4918-4279-a47c-50fdbcb74a04"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RigidBodyTools = "befc5f09-81d5-499c-a4b2-d0464ba9f9c8"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
CartesianGrids = "0.1.29"
CatViews = "1.0.0"
ColorTypes = "<0.10.1, 0.10, 0.11"
ConstrainedSystems = "0.3.8"
DocStringExtensions = "0.8.4, 0.9"
RecipesBase = "1.0"
Reexport = "0.2.0, 1"
RigidBodyTools = "0.5.6"
UnPack = "1.0.2"
julia = "1.6"
LinearAlgebra = "1.6"

[extras]
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Literate", "Plots"]
