[deps]
CartesianGrids = "3e975e5d-2cf8-4263-9573-8460aaf534d9"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ImmersedLayers = "cdc13194-334e-4e1c-bc8d-fc3a28509c85"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RigidBodyTools = "befc5f09-81d5-499c-a4b2-d0464ba9f9c8"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
CartesianGrids = "0.1.21"
LaTeXStrings = "^1.0, 1.1"
Plots = "1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20"
RigidBodyTools = "0.3.1"
UnPack = "1.0.2"
julia = "1.6"
